/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("AuthorsObjectPageObjectPage journey");

        opaTest("Navigate to AuthorsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheAuthorsList.onFilterBar().iExecuteSearch();

            Then.onTheAuthorsList.onTable().iCheckRows();
            When.onTheAuthorsList.onTable().iPressRow(0);

            Then.onTheAuthorsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheAuthorsObjectPage.iCheckSection({ section: "Main" });
            Then.onTheAuthorsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "name" });
            Then.onTheAuthorsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "bio" });
            Then.onTheAuthorsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "createdAt" });
            Then.onTheAuthorsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "createdBy" });
            Then.onTheAuthorsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "modifiedAt" });
            Then.onTheAuthorsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "modifiedBy" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});