/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BooksAuthorsObjectPageObjectPage journey");

        opaTest("Navigate to BooksAuthorsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheBooksList.onFilterBar().iExecuteSearch();

            Then.onTheBooksList.onTable().iCheckRows();
            When.onTheBooksList.onTable().iPressRow(0);

            Then.onTheBooksObjectPage.iSeeThisPage();
            Then.onTheBooksObjectPage.onTable({ property: "authors" }).iCheckRows();
            When.onTheBooksObjectPage.onTable({ property: "authors" }).iPressRow(0);

            Then.onTheBooksAuthorsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheBooksAuthorsObjectPage.iCheckSection({ section: "Main" });
            Then.onTheBooksAuthorsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "book_ID" });
            Then.onTheBooksAuthorsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "author_ID" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});